
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Booking extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_user
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_regular = new usu.widget.ButtonGlass();
        btn_bmember = new usu.widget.ButtonGlass();
        btn_event = new usu.widget.ButtonGlass();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1091, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setWarna(new java.awt.Color(0, 0, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled-1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ll.png"))); // NOI18N

        btn_regular.setForeground(new java.awt.Color(255, 255, 255));
        btn_regular.setText("BOOKING FOR REGULAR");
        btn_regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regularActionPerformed(evt);
            }
        });

        btn_bmember.setForeground(new java.awt.Color(255, 255, 255));
        btn_bmember.setText("BOOKING FOR MEMBER");
        btn_bmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bmemberActionPerformed(evt);
            }
        });

        btn_event.setForeground(new java.awt.Color(255, 255, 255));
        btn_event.setText("BOOKING FOR EVENT");
        btn_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eventActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/l1.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENU BOOKING LAPANGAN FUTSAL");

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_bmember, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(btn_event, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_event, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bmember, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 980, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG3.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1091, 960));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 1360, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regularActionPerformed
        Home.jDesktopPane1.removeAll();
        Home.jDesktopPane1.repaint();
        Form_booking_regular a = new Form_booking_regular();
        a.setVisible(true);
        Home.jDesktopPane1.add(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regularActionPerformed

    private void btn_bmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bmemberActionPerformed
        Home.jDesktopPane1.removeAll();
        Home.jDesktopPane1.repaint();
        Form_booking_member b = new Form_booking_member();
        b.setVisible(true);
        Home.jDesktopPane1.add(b);

    // TODO add your handling code here:
    }//GEN-LAST:event_btn_bmemberActionPerformed

    private void btn_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eventActionPerformed
        Home.jDesktopPane1.removeAll();
        Home.jDesktopPane1.repaint();
        Form_Event c = new Form_Event();
        c.setVisible(true);
        Home.jDesktopPane1.add(c);

    // TODO add your handling code here:
    }//GEN-LAST:event_btn_eventActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btn_bmember;
    private usu.widget.ButtonGlass btn_event;
    private usu.widget.ButtonGlass btn_regular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private usu.widget.glass.PanelGlass panelGlass1;
    // End of variables declaration//GEN-END:variables
}
