import Database.KoneksiDatabase;
import java.sql.ResultSet;

import Database.ResultSetTable;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class CetakData extends javax.swing.JInternalFrame {
    ResultSet rs;
    KoneksiDatabase con;
    /**
     * Creates new form Add_user
     */
    public CetakData() {
        initComponents();
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
        loadregular();
        loadmember();
        loadevent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_regular = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_member = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_event = new javax.swing.JTable();
        btn_laporan1 = new usu.widget.ButtonGlass();
        btn_laporan = new usu.widget.ButtonGlass();
        btn_laporan2 = new usu.widget.ButtonGlass();
        btn_laporan3 = new usu.widget.ButtonGlass();
        btn_laporan4 = new usu.widget.ButtonGlass();
        btn_laporan5 = new usu.widget.ButtonGlass();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1091, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_regular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_regular);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 740, 140));

        tabel_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel_member);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 740, 160));

        tabel_event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_event);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 740, 190));

        btn_laporan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan1.setText("Cetak Laporan Transaksi");
        btn_laporan1.setRoundRect(true);
        btn_laporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 180, 70));

        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Cetak Laporan Transaksi");
        btn_laporan.setRoundRect(true);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 180, 70));

        btn_laporan2.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan2.setText("Cetak Laporan Transaksi");
        btn_laporan2.setRoundRect(true);
        btn_laporan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 180, 70));

        btn_laporan3.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan3.setText("Delete");
        btn_laporan3.setRoundRect(true);
        btn_laporan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 180, 70));

        btn_laporan4.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan4.setText("Delete");
        btn_laporan4.setRoundRect(true);
        btn_laporan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 180, 70));

        btn_laporan5.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan5.setText("Delete");
        btn_laporan5.setRoundRect(true);
        btn_laporan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 180, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA BOOKING FOR MEMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA BOOKING FOR MEMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA BOOKING FOR REGULAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG3.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1091, 960));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 1360, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        cetak();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_laporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan1ActionPerformed
        cetak1();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporan1ActionPerformed

    private void btn_laporan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan2ActionPerformed
        cetak2();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporan2ActionPerformed

    private void btn_laporan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan3ActionPerformed
        try {
            String id=String.valueOf(tabel_event.getValueAt(tabel_event.getSelectedRow(),0));
                if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            con.queryDelete("tb_event","id_event="+id);

            }else{
                return;
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadevent();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporan3ActionPerformed

    private void btn_laporan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan4ActionPerformed
        try {
            String id=String.valueOf(tabel_member.getValueAt(tabel_member.getSelectedRow(),0));
                if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            con.queryDelete("tb_booking_member","id_booking_member="+id);

            }else{
                return;
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadmember();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporan4ActionPerformed

    private void btn_laporan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan5ActionPerformed
        try {
            String id=String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),0));
                if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            con.queryDelete("tb_booking_regular","id_regular="+id);

            }else{
                return;
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadregular();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporan5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btn_laporan;
    private usu.widget.ButtonGlass btn_laporan1;
    private usu.widget.ButtonGlass btn_laporan2;
    private usu.widget.ButtonGlass btn_laporan3;
    private usu.widget.ButtonGlass btn_laporan4;
    private usu.widget.ButtonGlass btn_laporan5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabel_event;
    private javax.swing.JTable tabel_member;
    private javax.swing.JTable tabel_regular;
    // End of variables declaration//GEN-END:variables

    public void cetak() {
        try {
            tabel_regular.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Data Transaksi Regular"), null);
        } catch (PrinterException ex) {
            Logger.getLogger(CetakData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cetak1() {
        try {
            tabel_member.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Data Transaksi Booking For Member"), null);
        } catch (PrinterException ex) {
            Logger.getLogger(CetakData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cetak2() {
        try {
            tabel_event.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Data Transaksi Booking For Event"), null);
        } catch (PrinterException ex) {
            Logger.getLogger(CetakData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    private void loadregular() {
        String namaKolom[] = {"tgl_booking","penyewa","lapangan","lama","jam_main","jam_selesai","total","dp","sisa"};
        rs=con.querySelect(namaKolom,"tb_booking_regular");
        tabel_regular.setModel(new ResultSetTable(rs));
    }
    
    private void loadmember() {
        String namaKolom[] = {"tgl_aktif","tgl_nonaktif","team","lapangan","lama","jam_main","jam_selesai","hari","total"};
        rs=con.querySelect(namaKolom,"tb_booking_member");
        tabel_member.setModel(new ResultSetTable(rs));
    }


    private void loadevent() {
        String namaKolom[] = {"penyewa","tgl_main","lama_hari","lapangan","jam","jam_main","jam_selesai","tgl_booking","harga","total"};
        rs=con.querySelect(namaKolom,"tb_event");
        tabel_event.setModel(new ResultSetTable(rs));
    }

}
