

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.PrintJob;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Form_booking_regular extends javax.swing.JInternalFrame {
    
    ResultSet rs;
    KoneksiDatabase con;
    /**
     * Creates new form Add_user
     */
    public Form_booking_regular() {
        con = new KoneksiDatabase(new Database.Parameter().HOST_DB, new Database.Parameter().USERNAME_DB, new Database.Parameter().PASSWORD_DB);
        initComponents();
        loadlapangan();
        loadTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j_booking = new com.toedter.calendar.JDateChooser();
        txt_penyewa = new javax.swing.JTextField();
        txt_lama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_main = new javax.swing.JTextField();
        txt_selesai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_regular = new javax.swing.JTable();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_dp = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_total = new usu.widget.ButtonGlass();
        jLabel15 = new javax.swing.JLabel();
        lbl_sisa = new javax.swing.JLabel();
        btn_sisa = new usu.widget.ButtonGlass();
        jLabel2 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_lapangan = new javax.swing.JLabel();
        lbl_jenis = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        box_kode = new javax.swing.JComboBox();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        btn_clear = new usu.widget.ButtonGlass();
        btn_save = new usu.widget.ButtonGlass();
        btn_cetak = new usu.widget.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1091, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setWarna(new java.awt.Color(0, 0, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Atas Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jam Main");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Booking");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jam Selesai");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lama");

        txt_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_penyewaActionPerformed(evt);
            }
        });

        txt_lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jam");

        txt_main.setText("00:00");
        txt_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mainActionPerformed(evt);
            }
        });

        txt_selesai.setText("00:00");
        txt_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_penyewa)
                            .addGroup(panelGlass1Layout.createSequentialGroup()
                                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGlass1Layout.createSequentialGroup()
                                        .addComponent(txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(j_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 74, Short.MAX_VALUE))))
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(j_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_penyewa, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_lama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_main, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_selesai))
                .addGap(96, 96, 96))
        );

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 400, 250));

        tabel_regular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Booking", "Tgl_booking", "Penyewa", "Lapangan", "harga", "Jam Main", "Jam Selesai", "Lama", "Total", "Dp", "Sisa"
            }
        ));
        tabel_regular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_regularMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_regular);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1070, 220));

        panelGlass2.setWarna(new java.awt.Color(0, 0, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DP");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sisa  ");

        txt_dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dpActionPerformed(evt);
            }
        });

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        btn_total.setForeground(new java.awt.Color(255, 255, 255));
        btn_total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calculator.png"))); // NOI18N
        btn_total.setText("Hitung Total");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rp.");

        lbl_sisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_sisa.setForeground(new java.awt.Color(204, 0, 0));
        lbl_sisa.setText("Tagihan");

        btn_sisa.setForeground(new java.awt.Color(255, 255, 255));
        btn_sisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calculator.png"))); // NOI18N
        btn_sisa.setText("Hitung Sisa");
        btn_sisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGlass2Layout.createSequentialGroup()
                                .addComponent(btn_sisa, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txt_dp)
                            .addComponent(btn_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_sisa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_dp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btn_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbl_sisa))
                .addGap(56, 56, 56))
        );

        getContentPane().add(panelGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 280, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA TRANSAKSI BOOKING FOR REGULAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 50));

        panelGlass3.setWarna(new java.awt.Color(0, 0, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Kode Lapangan");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nama Lapangan");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Jenis");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Harga sewa");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":  ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":  ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":  ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":  ");

        lbl_lapangan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_lapangan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lapangan.setText("lbl_lapangan");

        lbl_jenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_jenis.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jenis.setText("lbl_jenis");

        lbl_harga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_harga.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga.setText("lbl_harga");

        box_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_kodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass3Layout.createSequentialGroup()
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGlass3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_harga))
                            .addGroup(panelGlass3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_jenis))
                            .addGroup(panelGlass3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_lapangan)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(box_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(lbl_lapangan))
                .addGap(32, 32, 32)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(lbl_jenis))
                .addGap(32, 32, 32)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(lbl_harga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelGlass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 330, 250));

        panelGlass4.setWarna(new java.awt.Color(0, 0, 204));

        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash_box.png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        btn_cetak.setText("CETAK RESI");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(panelGlass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 810, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1091, 960));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1320, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_penyewaActionPerformed

    private void txt_lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamaActionPerformed

    private void txt_dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dpActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void box_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_kodeActionPerformed
        String st = (String) box_kode.getSelectedItem();
        ResultSet rst = con.querySelectAll("tb_lapangan", "id_lapangan='" + st + "'");
        try {
            while (rst.next()) {
                this.lbl_lapangan.setText(rst.getString("lapangan"));
                this.lbl_jenis.setText(rst.getString("jenis"));
                this.lbl_harga.setText(rst.getString("harga"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_booking_regular.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO 

    }//GEN-LAST:event_box_kodeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        save();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mainActionPerformed

    private void txt_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_selesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_selesaiActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        try {
            int lama = Integer.parseInt(txt_lama.getText());
            int harga = Integer.parseInt(lbl_harga.getText());
            int total = lama * harga;
            String jum = (Long.toString(total));
            txt_total.setText(jum);

        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, "Masukkan Lama Menyewa");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_totalActionPerformed

    private void btn_sisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sisaActionPerformed
        try {
            int sum = Integer.parseInt(txt_total.getText()); 
            int dp = Integer.parseInt(txt_dp.getText());   
            int sisa = sum - dp;                     
            String a = Integer.toString(sisa);
            lbl_sisa.setText(a);

        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, "Silahkan hitung kembali total pembayaran");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sisaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        resi();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void tabel_regularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_regularMouseClicked

        Date n = (Date) tabel_regular.getValueAt(tabel_regular.getSelectedRow(), 0);
        j_booking.setDate(n);
        txt_penyewa.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),1)));
        lbl_lapangan.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),2)));
        lbl_harga.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),3)));
        txt_main.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),4)));
        txt_selesai.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),5)));
        txt_lama.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),6)));
        txt_total.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),7)));
        txt_dp.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),8)));
        lbl_sisa.setText(String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),9)));
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_regularMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box_kode;
    private usu.widget.ButtonGlass btn_cetak;
    private usu.widget.ButtonGlass btn_clear;
    private usu.widget.ButtonGlass btn_save;
    private usu.widget.ButtonGlass btn_sisa;
    private usu.widget.ButtonGlass btn_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser j_booking;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_jenis;
    private javax.swing.JLabel lbl_lapangan;
    private javax.swing.JLabel lbl_sisa;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private javax.swing.JTable tabel_regular;
    private javax.swing.JTextField txt_dp;
    private javax.swing.JTextField txt_lama;
    private javax.swing.JTextField txt_main;
    private javax.swing.JTextField txt_penyewa;
    private javax.swing.JTextField txt_selesai;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    private void loadlapangan() {  // mengambil database
        rs = con.querySelectAll("tb_lapangan");
        try {
            while (rs.next()) {
                box_kode.addItem(rs.getString("id_lapangan"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Form_booking_regular.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void loadTabel(){
    String namaKolom[] = {"tgl_booking","penyewa","lapangan","harga","jam_main","jam_selesai","lama","total","dp","sisa"}; //,
        rs = con.querySelect(namaKolom, "tb_booking_regular");
        tabel_regular.setModel(new ResultSetTable(rs));
    }
    
    private void clear() {
        txt_penyewa.setText("");
        txt_lama.setText("");
        txt_main.setText("00:00");
        txt_selesai.setText("00:00");
        txt_total.setText("");
        txt_dp.setText("");

    }
    
    private void save() {
        try {
            java.util.Date tgl = (java.util.Date) this.j_booking.getDate();
            if( !new java.sql.Date(tgl.getTime()).toString().isEmpty() && !txt_penyewa.getText().isEmpty()&& !txt_main.getText().isEmpty()&& !txt_lama.getText().isEmpty()&& !txt_total.getText().isEmpty()&& !txt_dp.getText().isEmpty()&& !lbl_sisa.getText().isEmpty()){
                String kolom[] = {"tgl_booking","penyewa","lapangan","harga","jam_main","jam_selesai","lama","total","dp","sisa"};
                String isi[] = { new java.sql.Date(tgl.getTime()).toString(),txt_penyewa.getText(),lbl_lapangan.getText(),lbl_harga.getText(),txt_main.getText(),txt_selesai.getText(),txt_lama.getText(),txt_total.getText(),txt_dp.getText(),lbl_sisa.getText()};
                
                System.out.println( con.queryInsert("tb_booking_regular",kolom,isi));
               
                JOptionPane.showMessageDialog(this, "Data Transaksi Berhasil ditambahkan");
            }else{
                JOptionPane.showMessageDialog(this, "Data Transaksi Masih ada yang Kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error input data");
            System.out.println("salah");
        }
        loadTabel();
        clear();
    }
    
    
    public void resi(){
                
        Login su = new Login();

        PrintJob p = getToolkit().getPrintJob(su,"Report",null);
        Graphics g = p.getGraphics();

        try{
            //String id = String.valueOf(tabel_regular.getValueAt(tabel_regular.getSelectedRow(),0));
            String n = txt_penyewa.getText();
            rs=con.querySelectAll("tb_booking_regular","penyewa='"+n+"'");
            //String id = String.valueOf(table_transaksi1.getValueAt(table_transaksi1.getSelectedRow(),0));
        if(rs.next()){
            String id = rs.getString("id_regular");
            String nama = rs.getString("penyewa");
            String nom = rs.getString("dp");

            g.drawLine(10, 75, 580, 75);
            g.drawLine(10, 75, 10, 285);
            
            g.drawLine(580, 75, 580, 285);
            g.drawLine(10, 285, 580, 285);

            g.setFont(new Font("Serif",Font.BOLD,16));
            g.drawString("No.",100, 102);
            g.drawString(id, 140, 101 );
            g.drawString("_ _ _ _ _ _ _ _",135, 100);

            g.setFont(new Font("Serif",Font.PLAIN,13));
            g.drawString("Terima Dari", 100, 125);
            g.setFont(new Font("Serif",Font.BOLD,14));
            g.drawString(nama, 195, 124 );
            g.setFont(new Font("Serif",Font.PLAIN,13));
            g.drawString("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _", 188, 124);

            g.drawString("Uang Sebanyak", 100, 146);
            g.setColor(java.awt.Color.GRAY);
            for(int i=0; i<=6; i++)
                {g.drawString("______________________________________________________", 200-(i*2), 135+(i*2));}
            for(int i=0; i<=6; i++)
                {g.drawString("______________________________________________________", 200-(i*2), 151+(i*2));}

            g.setColor(java.awt.Color.BLACK);
            for(int i=0; i<=3; i++) 
                {g.drawString("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _", 100, 180+(i*14));}

            g.drawLine(100, 250, 350, 250);
            g.setFont(new Font("Serif",Font.BOLD,12));
            g.drawString("Terbilang Rp. ", 100, 264);
            g.setFont(new Font("Serif",Font.BOLD,14));
            g.drawString(nom, 205, 264 );
            for(int i=0; i<=6; i++)
                {g.setColor(java.awt.Color.GRAY);
                g.drawString("_____________________", 200-(i*2), 251+(i*2));}
            g.setColor(java.awt.Color.BLACK);
            
            g.drawLine(100, 270, 350, 270);
            g.drawLine(440, 270, 550, 270);

            p.end();
        }
        else{
            JOptionPane.showMessageDialog(this, "Gagal Cetak!!");
        }
        
        }catch(SQLException|HeadlessException e){
            JOptionPane.showMessageDialog(this, "Error!!");
        }
        
        dispose();
        Form_booking_regular fm = new Form_booking_regular();
        fm.setVisible(true);
    }
    
    
}

