/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        btn_logout.setVisible(false);
        btn_add_user.setVisible(false);
        btn_lapangan.setVisible(false);
        btn_booking.setVisible(false);
        btn_member.setVisible(false);
        btn_Jadwal.setVisible(true);
        btn_Cetak.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        btn_booking = new usu.widget.ButtonGlass();
        btn_member = new usu.widget.ButtonGlass();
        btn_exit = new usu.widget.ButtonGlass();
        btn_lapangan = new usu.widget.ButtonGlass();
        btn_login = new usu.widget.ButtonGlass();
        btn_add_user = new usu.widget.ButtonGlass();
        btn_logout = new usu.widget.ButtonGlass();
        btn_Jadwal = new usu.widget.ButtonGlass();
        btn_Cetak = new usu.widget.ButtonGlass();
        jDesktopPane1 = new BG();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI ZONE73");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setWarna(new java.awt.Color(0, 51, 204));
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_booking.setBackground(new java.awt.Color(255, 255, 255));
        btn_booking.setForeground(new java.awt.Color(255, 255, 255));
        btn_booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/boo.png"))); // NOI18N
        btn_booking.setText("BOOKING LAPANGAN");
        btn_booking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 183, 76));

        btn_member.setForeground(new java.awt.Color(255, 255, 255));
        btn_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mem.png"))); // NOI18N
        btn_member.setText("ADD MEMBER");
        btn_member.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 183, 76));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Off.png"))); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setToolTipText("");
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 180, 70));

        btn_lapangan.setForeground(new java.awt.Color(255, 255, 255));
        btn_lapangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lap.png"))); // NOI18N
        btn_lapangan.setText("DATA LAPANGAN");
        btn_lapangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_lapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapanganActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 183, 76));

        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIN.png"))); // NOI18N
        btn_login.setText("LOG IN");
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 183, 76));

        btn_add_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_user.png"))); // NOI18N
        btn_add_user.setText("ADD USER");
        btn_add_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_add_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 183, 76));

        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_out.png"))); // NOI18N
        btn_logout.setText("LOG OUT");
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 183, 76));

        btn_Jadwal.setBackground(new java.awt.Color(255, 255, 255));
        btn_Jadwal.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mem.png"))); // NOI18N
        btn_Jadwal.setText("DATA JADWAL");
        btn_Jadwal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JadwalActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_Jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 183, 76));

        btn_Cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        btn_Cetak.setText("Cetak Data");
        btn_Cetak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CetakActionPerformed(evt);
            }
        });
        panelGlass1.add(btn_Cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 183, 76));

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 82, 240, 620));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1091, 768));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 768));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/z.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed

        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Add_user fm = new Add_user();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_userActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        btn_logout.setVisible(false);
        btn_login.setVisible(true);
        btn_add_user.setVisible(false);
        btn_lapangan.setVisible(false);
        btn_booking.setVisible(false);
        btn_member.setVisible(false);
        btn_Jadwal.setVisible(true);
        btn_Cetak.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        jDesktopPane1.repaint();
        dispose();
        Login fm = new Login();
        fm.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_lapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapanganActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Data_lapangan fm = new Data_lapangan();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lapanganActionPerformed

    private void btn_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Add_member fm = new Add_member();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_memberActionPerformed

    private void btn_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Booking fm = new Booking();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bookingActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JadwalActionPerformed
        jDesktopPane1.repaint();
        dispose();
        Data_Jadwal dj = new Data_Jadwal();
        dj.setVisible(true);
        //jDesktopPane1.add(dj);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_JadwalActionPerformed

    private void btn_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CetakActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        CetakData fm = new CetakData();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btn_Cetak;
    private usu.widget.ButtonGlass btn_Jadwal;
    private usu.widget.ButtonGlass btn_add_user;
    private usu.widget.ButtonGlass btn_booking;
    private usu.widget.ButtonGlass btn_exit;
    private usu.widget.ButtonGlass btn_lapangan;
    private usu.widget.ButtonGlass btn_login;
    private usu.widget.ButtonGlass btn_logout;
    private usu.widget.ButtonGlass btn_member;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private usu.widget.glass.PanelGlass panelGlass1;
    // End of variables declaration//GEN-END:variables

    public void admin() {
        btn_logout.setVisible(true);
        btn_login.setVisible(false);
        btn_add_user.setVisible(true);
        btn_lapangan.setVisible(true);
        btn_booking.setVisible(false);
        btn_member.setVisible(false);
        btn_Jadwal.setVisible(false);
        btn_Cetak.setVisible(true);
    }

    public void operator() {
        btn_logout.setVisible(true);
        btn_login.setVisible(false);
        btn_add_user.setVisible(false);
        btn_lapangan.setVisible(false);
        btn_booking.setVisible(true);
        btn_member.setVisible(true);
        btn_Jadwal.setVisible(false);
        btn_Cetak.setVisible(false);
    }    
    






}
